### PR TITLE
check if gcloud command exists before calling it

### PR DESCRIPTION
**Pull request by TheRoyalTnetennba**
* Fixes https://github.com/googleapis/google-auth-library-ruby/issues/192
* Add double-quotes to linter rules and run `rubocop --auto-correct`

### CODE REVIEW

**Comment by quartzmo** [comment]
Just curious, is there any case to be made for emitting a warning if `gcloud` is not present?

**Comment by TheRoyalTnetennba** [comment]
> Just curious, is there any case to be made for emitting a warning if `gcloud` is not present?

I kind of preferred giving some sort of warning. It was removed in https://github.com/googleapis/google-auth-library-ruby/pull/184. :man_shrugging:

**Comment by quartzmo** [comment]
@TheRoyalTnetennba I remember now that the warning was a sore point.

**Comment by blowmage** [comment]
Changing the linter to double quotes seems orthogonal to adding a check for `gcloud` before calling it. Can the linter change be split into a separate PR?

**Comment by morgoth** [comment]
This fixes the case when `gcloud` is not installed.
However on Travis when I run tests, there is still output displayed:
```
ERROR: (gcloud.config.config-helper) You do not currently have an active account selected.
Please run:
  $ gcloud auth login
to obtain new credentials, or if you have already logged in with a
different account:
  $ gcloud config set account ACCOUNT
to select an already authenticated account to use.
```
I'm running tests on Travis using `xenial` distro

**Comment by morgoth** [comment]
@TheRoyalTnetennba any other idea how to fix it?

**Pull request closed without merging**
