### PR TITLE
add initial kokoro configs

### PR DESCRIPTION
**Pull request by TheRoyalTnetennba**

### CODE REVIEW

**Comment by TheRoyalTnetennba** [comment]
ping

**Comment by JustinBeckwith** [comment]
@chingor13 do you mind taking a look here?

**Comment by TheRoyalTnetennba** [comment]
@dazuma I'm hoping environmental issues. Will be looking at this failure, and the google-cloud-ruby failures.

**Comment by TheRoyalTnetennba** [comment]
For this library, the failures are all environment related (sort of). Being on GCE makes it hit different code paths on the tests, causing it to try and make real http requests which aren't allowed.

**Pull request merged**
