### PR TITLE
switch gcloud command to IO.popen from backticks

### PR DESCRIPTION
**Pull request by TheRoyalTnetennba**
Fixes https://github.com/googleapis/google-auth-library-ruby/issues/192

### CODE REVIEW

**Comment by TheRoyalTnetennba** [comment]
Ubuntu tests are failing b/c the docker image doesn't have latest ruby versions. I will update and then re-run

**Comment by morgoth** [comment]
Unfortunately on Travis it still outputs:
```
ERROR: (gcloud.config.config-helper) You do not currently have an active account selected.
Please run:
  $ gcloud auth login
to obtain new credentials, or if you have already logged in with a
different account:
  $ gcloud config set account ACCOUNT
to select an already authenticated account to use.
```
Not sure why

**Comment by TheRoyalTnetennba** [comment]
Is travis running with the --debug option? I haven't released the changes yet.

**Comment by morgoth** [comment]
No, also no RUBYOPT is set.

**Pull request merged**
