### PR TITLE
add google-style and refactor

### PR DESCRIPTION
**Pull request by TheRoyalTnetennba**

### CODE REVIEW

**Comment by blowmage** [comment]
Ubuntu looks like it is running 4 ruby versions, but OSx and Windows are only running 1 ruby version. Is that intentional?

**Comment by TheRoyalTnetennba** [comment]
> Ubuntu looks like it is running 4 ruby versions, but OSx and Windows are only running 1 ruby version. Is that intentional?

I have no control over the OSx environment. WIndows, I'm working on.

**Comment by y-yagi** [comment]
This has changed the required Ruby version. Ref: #208.
If this minimum version of the change is intentional, I think it should define `required_ruby_version` in the gemspec. 
It helps to find the appropriate gems.

**Comment by yahonda** [comment]
Updated #208 to define ` required_ruby_version` https://github.com/googleapis/google-auth-library-ruby/pull/208/commits/7c4209e9f397b1ef844916c175211fb47ef8de90 .

**Pull request merged**
